version: '3.7'

services:

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"   # MQTT
      - "8883:8883"   # MQTT over TLS
      - "8083:8083"   # MQTT over WebSocket
      - "8084:8084"   # MQTT over WebSocket with TLS
      - "18083:18083" # Dashboard
    environment:
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LISTENER__SSL__EXTERNAL=8883
      - EMQX_LISTENER__WS__EXTERNAL=8083
      - EMQX_LISTENER__WSS__EXTERNAL=8084
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    restart: always

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "9000:8000"
    networks:
      - heroze
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    volumes:
      - dynamodb-data:/var/dynamodb_local
  trooze_mongo:
    image: mongo:latest
    container_name: trooze_mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: asset
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - heroze
  java-services:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - heroze
    depends_on:
      - dynamodb
      - trooze_mongo
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/src/app/target

volumes:
  mongodb_data:
  dynamodb-data:
networks:
  heroze:
    external: true
    driver: bridge
